# Generated by Django 5.1.15 on 2026-10-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diprun',
            options={'ordering': ['-started_at', '-id']},
        ),
    ]
